---
version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    target_branch: "master"
    allowed_updates:
      - match:
          update_type: "security"
    version_requirement_updates: "off"
